from scrapy.item import Item, Field

class Index(Item):
    date = Field() 
    1 = Field()
    2 = Field()
    3 = Field()
    4 = Field()
    5 = Field()
    6 = Field()
    7 = Field()
    8 = Field()
    9 = Field()
    10 = Field()
    01 = Field()
    02 = Field()
    03 = Field()
    04 = Field()
    05 = Field()
    06 = Field()
    07 = Field()
    08 = Field()
    09 = Field()
    010 = Field()
